// Mocks generated by Mockito 5.0.14 from annotations
// in film_fluent/test/feature/favorite_list/data/repositories/favorite_list_repository_test.dart.
// Do not manually edit this file.

import 'package:film_fluent/feature/favorite_list/data/data_sources/favorite_list_local_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FavoriteListLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteListLocalDataSource extends _i1.Mock
    implements _i2.FavoriteListLocalDataSource {
  MockFavoriteListLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }
}
