// Mocks generated by Mockito 5.0.14 from annotations
// in film_fluent/test/feature/movie_detail/data/repositories/movie_detail_repository_test.dart.
// Do not manually edit this file.

import 'package:film_fluent/feature/movie_detail/data/data_sources/movie_detail_local_data_source.dart'
    as _i3;
import 'package:film_fluent/feature/movie_detail/data/data_sources/movie_detail_remote_data_source_impl.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MovieDetailRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailRemoteDataSourceImpl extends _i1.Mock
    implements _i2.MovieDetailRemoteDataSourceImpl {
  MockMovieDetailRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [MovieDetailLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailLocalDataSource extends _i1.Mock
    implements _i3.MovieDetailLocalDataSource {
  MockMovieDetailLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }
}
